DEFAULT_QUERIES = [
    "data analyst OR analista dati",
    "business analyst OR analista di business",
    "reporting analyst OR analista reporting",
    "analista finanziario",
    "analista ricerche di mercato",
    "analista ricerca",
    "analista operations",
    "analista pricing",
    "analista rischio",
    "analista credito",
    "analista frodi",
    "analista compliance",
    "analista investimenti",
    "analista ricerca azionaria",
    "contabile junior",
    "addetto contabilita",
    "specialista conti fornitori",
    "specialista conti clienti",
    "specialista paghe",
    "consulente fiscale junior",
    "revisore contabile",
    "controller finanziario",
    "specialista acquisti",
    "buyer",
    "pianificatore supply chain",
    "pianificatore domanda",
    "pianificatore scorte",
    "coordinatore di progetto",
    "project manager",
    "program manager",
    "product manager",
    "product owner",
    "responsabile operations",
    "assistente amministrativo",
    "assistente di direzione",
    "assistente virtuale",
    "responsabile ufficio",
    "specialista supporto clienti",
    "addetto servizio clienti",
    "specialista help desk",
    "specialista supporto tecnico",
    "addetto vendite interne",
    "specialista sviluppo vendite",
    "account manager",
    "specialista marketing",
    "specialista marketing digitale",
    "specialista seo",
    "specialista content marketing",
    "redattore contenuti",
    "copywriter",
    "redattore tecnico",
    "editor",
    "correttore bozze",
    "traduttore",
    "specialista localizzazione",
    "assistente legale",
    "assistente legale",
    "recruiter",
    "specialista talent acquisition",
    "specialista risorse umane",
    "generalista risorse umane",
    "specialista formazione e sviluppo",
    "progettista didattico",
    "assistente insegnante",
    "tutor online",
    "assistente ricerca",
    "analista politiche pubbliche",
    "economista",
    "ingegnere dati",
    "analista business intelligence",
    "analista bi",
    "data scientist",
    "ingegnere machine learning",
    "formatore ai",
    "prompt engineer",
    "specialista automazione",
    "specialista miglioramento processi",
    "knowledge manager",
    "specialista documentazione",
    "specialista crm",
    "customer success manager",
    "social media manager",
    "community manager",
    "giornalista",
    "redattore news",
    "redattore bandi",
    "redattore proposte",
    "underwriter",
    "specialista sinistri",
    "consulente prestiti",
    "analista immobiliare",
    "analista commerciale",
    "analista vendite",
    "analista pianificazione",
    "sviluppatore business intelligence",
    "sviluppatore report",
    "addetto inserimento dati",
    "specialista back office",
    "addetto operations",
]
