DEFAULT_QUERIES = [
    "data analyst",
    "business analyst",
    "reporting analyst",
    "financial analyst",
    "market research analyst",
    "research analyst",
    "operations analyst",
    "pricing analyst",
    "risk analyst",
    "credit analyst",
    "fraud analyst",
    "compliance analyst",
    "investment analyst",
    "equity research analyst",
    "junior accountant",
    "bookkeeper",
    "accounts payable specialist",
    "accounts receivable specialist",
    "payroll specialist",
    "tax associate",
    "auditor",
    "financial controller",
    "procurement specialist",
    "buyer",
    "supply chain planner",
    "demand planner",
    "inventory planner",
    "project coordinator",
    "project manager",
    "program manager",
    "product manager",
    "product owner",
    "operations manager",
    "administrative assistant",
    "executive assistant",
    "virtual assistant",
    "office manager",
    "customer support specialist",
    "customer service representative",
    "help desk specialist",
    "technical support specialist",
    "inside sales representative",
    "sales development representative",
    "account manager",
    "marketing specialist",
    "digital marketing specialist",
    "seo specialist",
    "content marketer",
    "content writer",
    "copywriter",
    "technical writer",
    "editor",
    "proofreader",
    "translator",
    "localization specialist",
    "paralegal",
    "legal assistant",
    "recruiter",
    "talent acquisition specialist",
    "hr specialist",
    "hr generalist",
    "learning and development specialist",
    "instructional designer",
    "teacher assistant",
    "online tutor",
    "research assistant",
    "policy analyst",
    "economist",
    "data engineer",
    "business intelligence analyst",
    "bi analyst",
    "data scientist",
    "machine learning engineer",
    "ai trainer",
    "prompt engineer",
    "automation specialist",
    "process improvement specialist",
    "knowledge manager",
    "documentation specialist",
    "crm specialist",
    "customer success manager",
    "social media manager",
    "community manager",
    "journalist",
    "news editor",
    "grant writer",
    "proposal writer",
    "underwriter",
    "claims specialist",
    "loan officer",
    "real estate analyst",
    "commercial analyst",
    "sales analyst",
    "planning analyst",
    "business intelligence developer",
    "report developer",
    "data entry specialist",
    "back office specialist",
    "operations associate",
]
